### ISSUE TITLE
How to install the script into a packer build

### ISSUE THREAD

**Issue by fmontaldo** [rgl/visual-studio-community-vagrant#2]
Hi 

I want to deploy this script in to a packer buidl for windows 10. I included the script like this:

   {
       "type": "powershell",
               "inline": ["/scripts/InstallVisualStudio.ps1"],
       "elevated_user": "vagrant",
       "elevated_password": "vagrant"
    },
    {
      "type": "windows-restart"
    }
Also I included this line at the begging:

$ConfirmPreference = "None"

But the build do not recognized the script

   virtualbox-iso: /scripts/InstallVisualStudio.ps1 : The term '/scripts/InstallVisualStudio.ps1' is not recognized as the name of a
    virtualbox-iso: cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify
    virtualbox-iso: that the path is correct and try again.
    virtualbox-iso: At C:\Windows\Temp\script-5bbe69c2-3ce5-d9d0-90b4-b1fb0fb1d405.ps1:1 char:1
    virtualbox-iso: + /scripts/InstallVisualStudio.ps1
    virtualbox-iso: + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    virtualbox-iso:     + CategoryInfo          : ObjectNotFound: (/scripts/InstallVisualStudio.ps1:String) [], CommandNotFoundException
    virtualbox-iso:     + FullyQualifiedErrorId : CommandNotFoundException
    virtualbox-iso:

Please tell me what I am doing wrong.

Regards 

Federico

**Comment by rgl** [comment]
packer is somewhat different than vagrant; one of the major differences is that packer does not mount the repository files inside the virtual machine and that's why your example wasn't working.

I'm closing this, because using packer is out-of-scope of this repository.
