### ISSUE TITLE
Support For Visual Studio 2015 as Option

### ISSUE THREAD

**Issue by loren-osborn** [rgl/visual-studio-community-vagrant#3]
# Feature Request:

It would be nice to support Visual Studio 2015 as an option. For now, I'm planning to checkout b1de18bf4d3b77c1e3b567ddf5f7697c4c2c11f8 and hope for the best, but an "official" option (or at least an alternate branch) would be very much appreciated.

**Comment by rgl** [comment]
I have to decline this request because I do not have the need for it.
